#!/bin/bash
#
# requires:
#  bash
#  yum
#
set -e

[[ -f /etc/sysconfig/network-scripts/ifcfg-br0 ]] && rm -f /etc/sysconfig/network-scripts/ifcfg-br0 || :

echo ASHIBA_ENV:${ASHIBA_ENV}
case "${ASHIBA_ENV}" in
openflow)
  cat <<-EOS > /etc/sysconfig/network-scripts/ifcfg-eth0
	DEVICE=eth0
	ONBOOT=yes
	NM_CONTROLLED=no
	BOOTPROTO=none
	DEVICETYPE=ovs
	TYPE=OVSPort
	OVS_BRIDGE=br0
	EOS

  cat <<-EOS > /etc/sysconfig/network-scripts/ifcfg-br0
	DEVICE=br0
	BOOTPROTO=static
	NM_CONTROLLED=no
	ONBOOT=yes
	DEVICETYPE=ovs
	TYPE=OVSBridge
	OVS_EXTRA="\\
	 set bridge     \${DEVICE} other_config:disable-in-band=true --\\
	 set-fail-mode  \${DEVICE} secure --\\
	 set-controller \${DEVICE} unix:/var/run/openvswitch/\${DEVICE}.controller
	"
	$([[ -z "${ip}"    ]] || echo IPADDR=${ip}      )
	$([[ -z "${gw}"    ]] || echo GATEWAY=${gw}     )
	$([[ -z "${net}"   ]] || echo NETWORK=${net}    )
	$([[ -z "${mask}"  ]] || echo NETMASK=${mask}   )
	$([[ -z "${bcast}" ]] || echo BROADCAST=${bcast})
	STP=off
	EOS
  ;;
netfilter|*)
  /opt/axsh/wakame-vdc/rpmbuild/helpers/setup-bridge-if.sh \
   --brname=br0  \
   --ifname=eth0
  ;;
esac
