#!/bin/bash
#
# requires:
#  bash
#  yum
#
set -e

[[ -f /etc/sysconfig/network-scripts/ifcfg-br0 ]] && rm -f /etc/sysconfig/network-scripts/ifcfg-br0 || :

/opt/axsh/wakame-vdc/rpmbuild/helpers/setup-bridge-if.sh \
 --brname=br0  \
 --ifname=eth0

# --ip=192.168.2.19 \
# --mask=255.255.255.0 \
# --gw=192.168.2.1
