#!/bin/bash
#
# requires:
#  bash
#  yum
#
set -e

yum clean metadata --disablerepo=* --enablerepo=wakame-vdc-rhel6
yum update  -y     --disablerepo=* --enablerepo=wakame-vdc-rhel6
yum install -y wakame-vdc-example-1box-experiment-vmapp-config
